// Generated by CoffeeScript 1.10.0
(function() {
  exports.user = require('./user');

  exports.group = require('./group');

  exports.problem = require('./problem');

  exports.contest = require('./contest');

  exports.message = require('./message');

  exports.submission = require('./submission');

  exports.feedback = require('./feedback');

  exports.solution = require("./solution");

  exports.api = require('./api');

}).call(this);

//# sourceMappingURL=index.js.map
