// Generated by CoffeeScript 1.9.2
(function() {
  exports.user = require('./user');

  exports.group = require('./group');

  exports.problem = require('./problem');

  exports.contest = require('./contest');

  exports.message = require('./message');

}).call(this);

//# sourceMappingURL=index.js.map
