// Generated by CoffeeScript 1.9.3
(function() {
  exports.user = require('./user');

  exports.group = require('./group');

  exports.problem = require('./problem');

  exports.contest = require('./contest');

  exports.message = require('./message');

  exports.submission = require('./submission');

  exports.judge = require('./judge');

}).call(this);

//# sourceMappingURL=index.js.map
