// Generated by CoffeeScript 1.9.3
(function() {
  var config, db;

  config = require('./config');

  db = require('./database')(config.database.name, config.database.username, config.database.password, config.database.config);

  require('./init')(db);

}).call(this);

//# sourceMappingURL=dbsync.js.map
