// Generated by CoffeeScript 1.9.2
(function() {
  require('./db')('form', 'root', 'alimengmengda', {
    host: 'localhost',
    dialect: 'mysql',
    port: 3306,
    timezone: '+08:00',
    pool: {
      max: 5,
      min: 0,
      idle: 10000
    }
  }).sync({
    force: true
  })["catch"](function(err) {
    return console.log(err.message);
  }).done(function() {
    console.log('Sync successfully!');
    return process.exit(0);
  });

}).call(this);

//# sourceMappingURL=dbsync.js.map
