// Generated by CoffeeScript 1.9.2
(function() {
  var LOGIN_PAGE;

  LOGIN_PAGE = '/user/login';

  module.exports = [
    function(req, res, next) {
      if (req.session.user === null) {
        req.flash('info', 'Please Login First');
        return res.redirect(LOGIN_PAGE);
      } else {
        return next();
      }
    }
  ];

}).call(this);

//# sourceMappingURL=middlewares.js.map
