// Generated by CoffeeScript 1.9.2
(function() {
  var controller, express, middlewares, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  middlewares = require('./middlewares');

  controller = require('./controller');

  router.use(middlewares);

  router.get('/', function(req, res) {
    return res.redirect(req.params.problemID + "/index");
  });

  router.get('/index/submission', controller.getSubmissions);

  router.get('/index', controller.getIndex);

  router.post('/index/submit', controller.postSubmission);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
