// Generated by CoffeeScript 1.9.2
(function () {
    exports.router = require('./router');

    exports.middlewares = require('./middlewares');

    exports.controller = require('./controller');

    exports.utils = require('./utils');

}).call(this);

//# sourceMappingURL=index.js.map
