// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = [
    function(req, res, next) {
      req.flash("info", "I am the first middleware of user index");
      req.flash("info", "I am the second middleware of user index");
      return next();
    }
  ];

}).call(this);

//# sourceMappingURL=middlewares.js.map
