// Generated by CoffeeScript 1.9.3
(function() {
  var controller, express, middlewares, modules, path, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  middlewares = require('./middlewares');

  controller = require('./controller');

  modules = require('./modules');

  path = require('path');

  router.use(middlewares);

  router.get('/', function(req, res) {
    return res.redirect('user/index');
  });

  router.get('/index', controller.getIndex);

  router.get('/login', controller.getLogin).post('/login', controller.postLogin);

  router.get('/register', controller.getRegister).post('/register', controller.postRegister);

  router.get('/logout', controller.getLogout);

  router.use('/:userID([0-9]+)', modules.detail.router);

  router.get('/binding', controller.getBinding);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
