// Generated by CoffeeScript 1.12.2
(function() {
  exports.contest = require('./contest');

  exports.user = require('./user');

  exports.bcpc = require('./bcpc');

  exports.acm_register = require('./acm-register');

}).call(this);

//# sourceMappingURL=index.js.map
