// Generated by CoffeeScript 1.9.2
(function() {
  var express, middlewares, modules, router;

  express = require('express');

  router = express.Router();

  middlewares = require('../middlewares');

  modules = require('../modules');

  router.use(middlewares);

  router.use('/user', modules.user.router);

  router.get('/', function(req, res) {
    return res.render('index', {
      title: 'OJ4TH',
      user: req.session.userID ? {
        userID: req.session.userID,
        nickname: req.session.nickname
      } : void 0
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
