// Generated by CoffeeScript 1.9.2
(function() {
  var express, middlewares, modules, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  middlewares = require('../middlewares');

  modules = require('../modules');

  router.use(middlewares);

  router.use('/user', modules.user.router);

  router.use('/group', modules.group.router);

  router.use('/problem', modules.problem.router);

  router.get('/', function(req, res) {
    return res.render('index', {
      title: 'OJ4TH',
      user: req.session.user
    });
  });

  module.exports = router;

}).call(this);

//# sourceMappingURL=index.js.map
