// Generated by CoffeeScript 1.9.2
(function() {
  var EDIT_PAGE, HOME_PAGE, INDEX_PAGE, LOGIN_PAGE, UPDATE_PWD_PAGE;

  HOME_PAGE = '/';

  UPDATE_PWD_PAGE = 'updatepw';

  EDIT_PAGE = 'edit';

  INDEX_PAGE = '.';

  LOGIN_PAGE = './login';

  exports.getIndex = function(req, res) {
    var User;
    User = global.db.models.user;
    return User.find(req.param.userID).then(function(user) {
      if (user) {
        return res.render('user', {
          title: 'Your userID=' + req.param.userID,
          user: {
            email: user.username,
            nickname: user.nickname,
            school: user.school,
            college: user.college,
            description: user.description,
            student_id: user.student_id
          }
        });
      } else {
        req.flash('info', 'unknown user');
        return req.redirect(HOME_PAGE);
      }
    })["catch"](function(err) {
      req.flash('info', err.message);
      return res.redirect(HOME_PAGE);
    });
  };

  exports.getEdit = function(req, res) {
    var User;
    User = global.db.models.user;
    return User.find(req.param.userID).then(function(user) {
      if (user) {
        return res.render('user_edit', {
          title: 'You are at EDIT page',
          user: {
            email: user.username,
            nickname: user.nickname,
            school: user.school,
            college: user.college,
            description: user.description,
            student_id: user.student_id
          }
        });
      } else {
        req.flash('info', 'unknown user');
        return req.redirect(INDEX_PAGE);
      }
    })["catch"](function(err) {
      req.flash('info', err.message);
      return res.redirect(INDEX_PAGE);
    });
  };

  exports.postEdit = function(req, res) {
    var User;
    User = global.db.models.user;
    return User.find(req.param.userID).then(function(user) {
      if (user) {
        if (req.param.nickname) {
          user.nickname = req.param.nickname;
        }
        if (req.param.school) {
          user.school = req.param.school;
        }
        if (req.param.college) {
          user.college = req.param.college;
        }
        if (req.param.description) {
          user.description = req.param.description;
        }
        return user.save().then(function() {
          req.flash('info', 'You have updated your info');
          return res.redirect('.');
        });
      } else {
        req.flash('info', 'unknown user');
        return res.redirect(INDEX_PAGE);
      }
    })["catch"](function(err) {
      req.flash('info', err.message);
      return res.redirect(INDEX_PAGE);
    });
  };

  exports.postPassword = function(req, res) {
    var User;
    User = global.db.models.user;
    return User.find(req.param.userID).then(function(user) {
      if (req.param.oldPwd && req.param.oldPwd === req.param.newPwd) {
        user.password = req.param.newPwd;
        return user.save().then(function() {
          delete req.session.userID;
          delete req.session.nickname;
          req.flash('info', 'You have updated your password, please login again');
          return res.redirect(LOGIN_PAGE);
        });
      } else {
        req.flash('info', 'Wrong password');
        return res.redirect(UPDATE_PWD_PAGE);
      }
    })["catch"](function(err) {
      req.flash('info', err.message);
      return res.redirect(INDEX_PAGE);
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
