// Generated by CoffeeScript 1.9.2
(function() {
  exports.getIndex = function(req, res) {
    var User;
    User = global.db.models.user;
    return User.find(req.param.userID.then(function(user) {
      return res.render('index', {
        title: 'Your userID=' + req.param.userID,
        user: {
          email: user.username,
          nickname: user.nickname,
          school: user.school,
          college: user.college,
          description: user.description,
          student_id: user.student_id
        }
      });
    }));
  };

  exports.getEdit = function(req, res) {
    return res.render('index', {
      title: 'You are at EDIT page'
    });
  };

  exports.postEdit = function(req, res) {
    var User;
    User = global.db.models.user;
    return User.find(req.param.userID.then(function(user) {
      if (req.param.nickname) {
        user.nickname = req.param.nickname;
      }
      if (req.param.school) {
        user.school = req.param.school;
      }
      if (req.param.college) {
        user.college = req.param.college;
      }
      if (req.param.description) {
        user.description = req.param.description;
      }
      return user.save().then(function() {
        return res.render('index', {
          title: 'You have updated your info'
        });
      });
    }));
  };

  exports.postPassword = function(req, res) {
    var User;
    User = global.db.models.user;
    return User.find(req.param.userID.then(function(user) {
      if (req.param.oldPwd && req.param.oldPwd === req.param.newPwd) {
        user.password = req.param.newPwd;
      }
      return user.save().then(function() {
        return res.render('index', {
          title: 'You have updated your password'
        });
      });
    }));
  };

}).call(this);

//# sourceMappingURL=controller.js.map
