// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = [
    function(req, res, next) {
      console.log('I am the first middleware of index');
      return next();
    }, function(req, res, next) {
      console.log('I am the second middleware of index');
      return next();
    }
  ];

}).call(this);

//# sourceMappingURL=index.js.map
