// Generated by CoffeeScript 1.9.2
(function() {
  var HOME_PAGE, LOGIN_PAGE, myUtils;

  myUtils = require('./utils');

  LOGIN_PAGE = 'user/login';

  HOME_PAGE = '/';

  exports.getIndex = function(req, res) {
    var Message;
    if (!req.session.user) {
      throw new myUtils.Error.UnknownUser();
    }
    Message = global.db.models.message;
    return Message.findAll({
      where: {
        user_id: req.session.user.id
      },
      order: [['created_at', 'DESC']]
    }).then(function(messages) {
      req.flash('info', 'message success');
      return res.render('message/index', {
        title: 'Message List',
        user: req.session.user,
        messages: messages
      });
    })["catch"](myUtils.Error.UnknownUser, function(err) {
      console.log(err);
      req.flash('info', "Please Login First!");
      return res.redirect(LOGIN_PAGE);
    })["catch"](function(err) {
      console.log(err.message);
      req.flash('info', "Unknown Error!");
      return res.redirect(HOME_PAGE);
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
