// Generated by CoffeeScript 1.10.0
(function() {
  var HOME_PAGE, LOGIN_PAGE, Promise;

  Promise = require('sequelize').Promise;

  LOGIN_PAGE = 'user/login';

  HOME_PAGE = '/';

  exports.getIndex = function(req, res) {
    var Message;
    if (!req.session.user) {
      throw new global.myErrors.UnknownUser();
    }
    Message = global.db.models.message;
    return Message.findAll({
      where: {
        user_id: req.session.user.id
      },
      order: [['created_at', 'DESC'], ['id', 'DESC']]
    }).then(function(messages) {
      req.flash('info', 'message success');
      return res.render('message/index', {
        title: 'Message List',
        user: req.session.user,
        messages: messages
      });
    })["catch"](global.myErrors.UnknownUser, function(err) {
      req.flash('info', err.messages);
      return res.redirect(LOGIN_PAGE);
    })["catch"](function(err) {
      console.log(err.message);
      err.message = "未知错误";
      return res.render('error', {
        error: err
      });
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
