// Generated by CoffeeScript 1.9.2
(function() {
  var Sequelize, path;

  Sequelize = require('sequelize');

  path = require('path');

  module.exports = function(database, username, password, config) {
    var Contest, ContestProblemList, Group, Judge, Membership, Problem, Submission, SubmissionCode, User, sequelize;
    sequelize = new Sequelize(database, username, password, config);
    Contest = sequelize["import"](path.join(__dirname, 'models/contest'));
    ContestProblemList = sequelize["import"](path.join(__dirname, 'models/contest-problem-list'));
    Group = sequelize["import"](path.join(__dirname, 'models/group'));
    Judge = sequelize["import"](path.join(__dirname, 'models/judge'));
    Membership = sequelize["import"](path.join(__dirname, 'models/membership'));
    Problem = sequelize["import"](path.join(__dirname, 'models/problem'));
    Submission = sequelize["import"](path.join(__dirname, 'models/submission'));
    SubmissionCode = sequelize["import"](path.join(__dirname, 'models/submission_code'));
    User = sequelize["import"](path.join(__dirname, 'models/user'));
    Contest.hasOne(User, {
      as: 'creator'
    });
    Contest.hasOne(Group);
    return sequelize;
  };

}).call(this);

//# sourceMappingURL=index.js.map
