// Generated by CoffeeScript 1.12.6
(function() {
  exports.getTags = function(req, res) {
    return global.db.Promise.resolve().then(function() {
      return global.myUtils.findAllProblem_tag(req.params.problemID).then(function(problem_tags) {
        return res.json(problem_tags);
      });
    })["catch"](function(err) {
      res.status(err.status || 400);
      return res.json({
        error: err.message
      });
    });
  };

  exports.postTags = function(req, res) {
    var currentTag;
    currentTag = void 0;
    return global.db.Promise.resolve().then(function() {
      return global.myUtils.findProblem_tag(req.params.problemID, req.body.content);
    }).then(function(ifRelationExit) {
      if (ifRelationExit) {
        return res.json("关系已存在！");
      } else {
        return global.myUtils.findTag(req.body.content).then(function(ifTagExit) {
          if (!ifTagExit) {
            global.myUtils.createTag(req.body.content);
          }
          return global.myUtils.createProblem_tag(req.body.content, req.params.problemID, req.body.weight).then(function(problem_tag) {
            return res.json(problem_tag.get({
              plasin: true
            }));
          });
        });
      }
    })["catch"](function(err) {
      res.status(err.status || 400);
      return res.json({
        error: err.message
      });
    });
  };

  exports.postcreateTags = function(req, res) {
    var currentTag;
    currentTag = void 0;
    return global.db.Promise.resolve().then(function() {
      return global.myUtils.findTag(req.body.content);
    }).then(function(ifRelationExit) {
      if (ifRelationExit) {
        return res.json("该标签已存在！");
      } else {
        return global.myUtils.createTag(req.body.content).then(function(tag) {
          return res.json(tag.get({
            plasin: true
          }));
        });
      }
    })["catch"](function(err) {
      res.status(err.status || 400);
      return res.json({
        error: err.message
      });
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
