// Generated by CoffeeScript 1.9.3
(function() {
  var HOME_PAGE, INDEX_PAGE, LOGIN_PAGE, myUtils;

  myUtils = require('./utils');

  INDEX_PAGE = 'index';

  LOGIN_PAGE = 'user/login';

  HOME_PAGE = '/';

  exports.postTask = function(req, res) {
    return myUtils.auth(req.body.judge).then(function() {});
  };

}).call(this);

//# sourceMappingURL=controller.js.map
