// Generated by CoffeeScript 1.10.0
(function() {
  var HOME_PAGE, INDEX_PAGE, LOGIN_PAGE;

  INDEX_PAGE = 'index';

  LOGIN_PAGE = 'user/login';

  HOME_PAGE = '/';

  exports.getIndex = function(req, res) {
    var Submission, User, currentUser;
    User = global.db.models.user;
    Submission = global.db.models.submission;
    currentUser = void 0;
    return global.db.Promise.resolve().then(function() {
      if (req.session.user) {
        return User.find(req.session.user.id);
      }
    }).then(function(user) {
      currentUser = user;
      if (!currentUser) {
        return [];
      }
    }).then(function() {
      return global.myUtils.getRankCount(void 0, void 0).then(function(Counts) {
        return global.myUtils.getRankName0(Counts).then(function(usercounts0) {
          return global.myUtils.getRankName1(Counts).then(function(usercounts1) {
            return global.myUtils.getRankName2(Counts).then(function(usercounts2) {
              return global.myUtils.getRankName3(Counts).then(function(usercounts3) {
                return global.myUtils.getRankName4(Counts).then(function(usercounts4) {
                  return global.myUtils.getRankName5(Counts).then(function(usercounts5) {
                    return global.myUtils.getRankName6(Counts).then(function(usercounts6) {
                      return global.myUtils.getRankName7(Counts).then(function(usercounts7) {
                        return global.myUtils.getRankName8(Counts).then(function(usercounts8) {
                          return global.myUtils.getRankName9(Counts).then(function(usercounts9) {
                            return global.myUtils.getDoRankCount(void 0, void 0).then(function(DoCounts) {
                              return global.myUtils.getRankName0(DoCounts).then(function(userdocounts0) {
                                return global.myUtils.getRankName1(DoCounts).then(function(userdocounts1) {
                                  return global.myUtils.getRankName2(DoCounts).then(function(userdocounts2) {
                                    return global.myUtils.getRankName3(DoCounts).then(function(userdocounts3) {
                                      return global.myUtils.getRankName4(DoCounts).then(function(userdocounts4) {
                                        return global.myUtils.getRankName5(DoCounts).then(function(userdocounts5) {
                                          return global.myUtils.getRankName6(DoCounts).then(function(userdocounts6) {
                                            return global.myUtils.getRankName7(DoCounts).then(function(userdocounts7) {
                                              return global.myUtils.getRankName8(DoCounts).then(function(userdocounts8) {
                                                return global.myUtils.getRankName9(DoCounts).then(function(userdocounts9) {
                                                  return res.render('rank/index', {
                                                    title: 'rank',
                                                    user: req.session.user,
                                                    Counts: Counts,
                                                    DoCounts: DoCounts,
                                                    Usercounts0: usercounts0,
                                                    Usercounts1: usercounts1,
                                                    Usercounts2: usercounts2,
                                                    Usercounts3: usercounts3,
                                                    Usercounts4: usercounts4,
                                                    Usercounts5: usercounts5,
                                                    Usercounts6: usercounts6,
                                                    Usercounts7: usercounts7,
                                                    Usercounts8: usercounts8,
                                                    Usercounts9: usercounts9,
                                                    Userdocounts0: userdocounts0,
                                                    Userdocounts1: userdocounts1,
                                                    Userdocounts2: userdocounts2,
                                                    Userdocounts3: userdocounts3,
                                                    Userdocounts4: userdocounts4,
                                                    Userdocounts5: userdocounts5,
                                                    Userdocounts6: userdocounts6,
                                                    Userdocounts7: userdocounts7,
                                                    Userdocounts8: userdocounts8,
                                                    Userdocounts9: userdocounts9
                                                  });
                                                });
                                              });
                                            });
                                          });
                                        });
                                      });
                                    });
                                  });
                                });
                              });
                            });
                          });
                        });
                      });
                    });
                  });
                });
              });
            });
          });
        });
      });
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
