// Generated by CoffeeScript 1.12.6
(function() {
  var HOME_PAGE, INDEX_PAGE, LOGIN_PAGE;

  INDEX_PAGE = 'index';

  LOGIN_PAGE = 'user/login';

  HOME_PAGE = '/';

  exports.getIndex = function(req, res) {
    var Submission, User, currentUser;
    User = global.db.models.user;
    Submission = global.db.models.submission;
    currentUser = void 0;
    global.myUtils.getDoRankCountR().then(function(results) {
      console.log(results[0].creator.dataValues.nickname);
      console.log(results[1].creator.dataValues.nickname);
      console.log(results[2].creator.dataValues.nickname);
      console.log(results[3].creator.dataValues.nickname);
      console.log(results[4].creator.dataValues.nickname);
      console.log(results[5].creator.dataValues.nickname);
      console.log(results[6].creator.dataValues.nickname);
      console.log(results[7].creator.dataValues.nickname);
      console.log(results[8].creator.dataValues.nickname);
      return console.log(results[9].creator.dataValues.nickname);
    });
    return global.db.Promise.resolve().then(function() {
      if (req.session.user) {
        return User.find(req.session.user.id);
      }
    }).then(function(user) {
      currentUser = user;
      if (!currentUser) {
        return [];
      }
    }).then(function() {
      return global.myUtils.getSolutionCount().then(function(Results) {
        return global.myUtils.getRankCount().then(function(Counts) {
          return global.myUtils.getDoRankCount().then(function(DoCounts) {
            return global.myUtils.getRankCountR().then(function(CountsR) {
              return global.myUtils.getDoRankCountR().then(function(DoCountsR) {
                return global.myUtils.getSolutionCountR().then(function(ResultsR) {
                  return res.render('rank/index', {
                    title: 'rank',
                    user: req.session.user,
                    Counts: Counts,
                    CountsR: CountsR,
                    DoCounts: DoCounts,
                    DoCountsR: DoCountsR,
                    Results: Results,
                    ResultsR: ResultsR
                  });
                });
              });
            });
          });
        });
      });
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
