// Generated by CoffeeScript 1.12.6
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('basic_rank', {
      id: {
        type: DataTypes.INTEGER,
        allowNull: false,
        primaryKey: true,
        unique: true
      },
      COUNT: {
        type: DataTypes.INTEGER,
        allowNUll: false
      }
    }, {
      underscored: true,
      freezeTableName: false,
      timestamps: false
    });
  };

}).call(this);

//# sourceMappingURL=basic_rank.js.map
