// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('feedback', {
      title: {
        type: DataTypes.TEXT('long'),
        allowNull: false,
        validate: {
          notEmpty: true
        }
      },
      content: {
        type: DataTypes.TEXT('long'),
        allowNull: false,
        defaultValue: ""
      }
    }, {
      timestamps: false,
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=feedback.js.map
