// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('group', {
      name: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
        validate: {
          notEmpty: true
        }
      },
      description: {
        type: DataTypes.TEXT
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=group.js.map
