// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('issue_reply', {
      content: {
        type: DataTypes.TEXT('long'),
        allowNull: false,
        validate: {
          notEmpty: true
        }
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=issue-reply.js.map
