// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('membership', {
      access_level: {
        type: DataTypes.ENUM('member', 'admin', 'owner'),
        defaultValue: 'member',
        allowNull: false
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=membership.js.map
