// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('membership', {
      access_level: {
        type: DataTypes.ENUM('verifying', 'member', 'admin', 'owner'),
        defaultValue: 'verifying',
        allowNull: false
      },
      user_id: {
        type: DataTypes.INTEGER,
        unique: 'user_group'
      },
      group_id: {
        type: DataTypes.INTEGER,
        unique: 'user_group'
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=membership.js.map
