// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('message', {
      title: {
        type: DataTypes.TEXT,
        allowNull: false
      },
      content: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      status: {
        type: DataTypes.ENUM("unread", "read"),
        defaultValue: "unread",
        allowNull: false
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=message.js.map
