// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('message', {
      content: {
        type: DataTypes.TEXT('long'),
        allowNull: false,
        validate: {
          notEmpty: true
        }
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=message.js.map
