// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize) {
    return sequelize.define('problem_tag', {}, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=problem-tag.js.map
