// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('problem', {
      title: {
        type: DataTypes.STRING,
        allowNull: false,
        unique: true,
        validate: {
          notEmpty: true
        }
      },
      access_level: {
        type: DataTypes.ENUM('private', 'protect', 'public'),
        defaultValue: 'private'
      },
      description: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      test_setting: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      difficulty: {
        type: DataTypes.DECIMAL(10, 5)
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=problem.js.map
