// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('problem_tag', {}, {
      timestamps: false,
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=problem-tag.js.map
