// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('recommendation', {
      score: {
        type: DataTypes.FLOAT,
        allowNull: false,
        validate: {
          min: -100
        },
        defaultValue: 0
      },
      user_id: {
        type: DataTypes.INTEGER,
        unique: 'user_recommendation_problem'
      },
      problem_id: {
        type: DataTypes.INTEGER,
        unique: 'user_recommendation_problem'
      }
    }, {
      timestamps: true,
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=recommendation.js.map
