// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('solution', {
      title: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
          notEmpty: true
        }
      },
      access_level: {
        type: DataTypes.STRING,
        defaultValue: 'private'
      },
      content: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      source: {
        type: DataTypes.TEXT('long'),
        allowNull: false
      },
      secret_limit: {
        type: DataTypes.DATE
      },
      category: {
        type: DataTypes.STRING
      },
      user_tag: {
        type: DataTypes.STRING
      },
      practice_time: {
        type: DataTypes.INTEGER
      },
      score: {
        type: DataTypes.INTEGER
      },
      influence: {
        type: DataTypes.INTEGER
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=solution.js.map
