// Generated by CoffeeScript 1.9.3
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('submission_code', {
      content: {
        type: DataTypes.STRING,
        allowNull: false
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=submission_code.js.map
