// Generated by CoffeeScript 1.9.2
(function() {
  var CONTEST_PAGE, HOME_PAGE, INDEX_PAGE, LOGIN_PAGE, MEMBER_PAGE, PROBLEM_PAGE, myUtils;

  myUtils = require('./utils');

  HOME_PAGE = '/';

  MEMBER_PAGE = 'member';

  CONTEST_PAGE = 'contest';

  PROBLEM_PAGE = 'problem';

  INDEX_PAGE = '.';

  LOGIN_PAGE = '/user/login';

  exports.getIndex = function(req, res) {
    var Group, User;
    Group = global.db.models.group;
    User = global.db.models.user;
    return Group.find(req.param.groupID, {
      include: [
        {
          model: User,
          as: 'creator'
        }
      ]
    }).then(function(group) {
      var ref;
      if (!group) {
        throw new myUtils.Error.UnknownGroup();
      }
      if ((ref = group.access_level) !== 'protect' && ref !== 'public') {
        throw new myUtils.Error.UnknownGroup();
      }
      return res.render('group/detail', {
        user: req.session.user,
        group: group
      });
    })["catch"](myUtils.Error.UnknownGroup, function(err) {
      req.flash('info', err.message);
      return res.redirect(INDEX_PAGE);
    })["catch"](function(err) {
      console.log(err);
      req.flash('info', "Unknown Error!");
      return res.redirect(INDEX_PAGE);
    });
  };

  exports.getMember = function(req, res) {
    var Group, User;
    Group = global.db.models.group;
    User = global.db.models.user;
    return Group.find(req.param.groupID, {
      include: [
        {
          model: User,
          through: {
            where: {
              access_level: ['member', 'admin', 'owner']
            }
          }
        }
      ]
    }).then(function(group) {
      var ref;
      if (!group) {
        throw new myUtils.Error.UnknownGroup();
      }
      if ((ref = group.access_level) !== 'protect' && ref !== 'public') {
        throw new myUtils.Error.UnknownGroup();
      }
      return res.render('group/member', {
        user: req.session.user,
        group: group
      });
    })["catch"](myUtils.Error.UnknownGroup, function(err) {
      req.flash('info', err.message);
      return res.redirect(INDEX_PAGE);
    })["catch"](function(err) {
      console.log(err);
      req.flash('info', "Unknown Error!");
      return res.redirect(INDEX_PAGE);
    });
  };

  exports.getProblem = function(req, res) {
    return res.render('index', {
      titile: "Problems of " + req.param.groupID
    });
  };

  exports.getContest = function(req, res) {
    return res.render('index', {
      titile: "Contests of " + req.param.groupID
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
