// Generated by CoffeeScript 1.9.2
(function() {
  var controller, express, middlewares, router;

  express = require('express');

  router = express.Router();

  middlewares = require('./middlewares');

  controller = require('./controller');

  router.use(middlewares);

  router.get('/', function(req, res) {
    return res.redirect(req.param.groupID + "/index");
  });

  router.get('/index', controller.getIndex);

  router.get('/member', controller.getMember);

  router.get('/join', controller.getJoin);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
