// Generated by CoffeeScript 1.9.2
(function() {
  var CONTEST_PAGE, HOME_PAGE, LOGIN_PAGE, myUtils;

  myUtils = require('./utils');

  LOGIN_PAGE = '/user/login';

  HOME_PAGE = '/';

  CONTEST_PAGE = '/contest';

  module.exports = [
    function(req, res, next) {
      return next();
    }
  ];

}).call(this);

//# sourceMappingURL=middlewares.js.map
