// Generated by CoffeeScript 1.9.3
(function() {
  var controller, express, middlewares, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  middlewares = require('./middlewares');

  controller = require('./controller');

  router.use(middlewares);

  router.get('/', function(req, res) {
    return res.redirect('submission/index');
  }).get('/index', controller.getIndex).get('/:submissionID([0-9]+)', controller.getSubmission);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
