// Generated by CoffeeScript 1.10.0
(function() {
  var controller, express, middlewares, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  middlewares = require('./middlewares');

  controller = require('./controller');

  router.use(middlewares);

  router.get('/', function(req, res) {
    return res.redirect('submission/index');
  }).get('/index', controller.getIndex).post('/index', controller.postIndex).get('/:submissionID([0-9]+)', controller.getSubmission).post('/getSubmissionApi', controller.postSubmissionApi).get('/:submissionID([0-9]+)/solution', controller.getSolution).post('/:submissionID([0-9]+)/solution', controller.postSolution).get('/:submissionID([0-9]+)/praise', controller.getPraise);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
