// Generated by CoffeeScript 1.9.3
(function() {
  var controller, express, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  controller = require('./controller');

  router.get('/:contestId', controller.getContest).get('/:contestId/rank', controller.getRank).get('/:contestId/submissions', controller.getSubmissions).post('/:contestId/submissions', controller.postSubmissions);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
