// Generated by CoffeeScript 2.2.3
(function() {
  var controller, express, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  controller = require('./controller');

  router.get('/server_time', controller.getTime).get('/:contestId', controller.getContest).get('/:contestId/rank', controller.getRank).get('/:contestId/submissions', controller.getSubmissions).get('/:contestId/submission/:submissionId', controller.getSubmission).post('/:contestId/submissions', controller.postSubmissions).get('/:contestId/issues', controller.getIssues).post('/:contestId/issues', controller.postIssues);

  module.exports = router;

}).call(this);
