// Generated by CoffeeScript 1.9.2
(function() {
  var CREATE_PAGE, HOME_PAGE, INDEX_PAGE, LOGIN_PAGE, myUtils, passwordHash;

  passwordHash = require('password-hash');

  myUtils = require('./utils');

  HOME_PAGE = '/';

  CREATE_PAGE = 'create';

  INDEX_PAGE = '.';

  LOGIN_PAGE = '/user/login';

  exports.getIndex = function(req, res) {
    return res.render('index', {
      title: 'You have got group index here'
    });
  };

  exports.getCreate = function(req, res) {
    return res.render('group/create', {
      title: 'create group'
    });
  };

  exports.postCreate = function(req, res) {
    var Group, User, form;
    form = {
      name: req.body.name,
      description: req.body.description
    };
    User = global.db.models.user;
    Group = global.db.models.group;
    return global.db.Promise.resolve().then(function() {
      if (!req.session.user) {
        throw new myUtils.Error.UnknownUser();
      }
      return User.find(req.session.user.id);
    }).then(function(user) {
      var group;
      if (!user) {
        throw new myUtils.Error.UnknownUser();
      }
      form.creator_id = user.id;
      group = Group.build(form);
      return group.save();
    }).then(function() {
      req.flash('info', 'create group successfully');
      return res.redirect(HOME_PAGE);
    })["catch"](myUtils.Error.UnknownUser, function(err) {
      req.flash('info', err.message);
      return res.redirect(LOGIN_PAGE);
    })["catch"](function(err) {
      console.log(err);
      req.flash('info', err.message);
      return res.redirect(CREATE_PAGE);
    });
  };

}).call(this);

//# sourceMappingURL=controller.js.map
