// Generated by CoffeeScript 1.9.2
(function() {
  var controller, express, middlewares, modules, router;

  express = require('express');

  router = express.Router();

  middlewares = require('./middlewares');

  controller = require('./controller');

  modules = require('./modules');

  router.use(middlewares);

  router.get('/', function(req, res) {
    return res.redirect('group/index');
  });

  router.get('/index', controller.getIndex);

  router.get('/create', controller.getCreate).post('/create', controller.postCreate);

  router.param('groupID', function(req, res, next, id) {
    req.param.groupID = id;
    return next();
  });

  router.use('/:groupID', modules.detail.router);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
