// Generated by CoffeeScript 1.9.2
(function() {
  var UnknownUser,
    extend = function(child, parent) { for (var key in parent) { if (hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    hasProp = {}.hasOwnProperty;

  UnknownUser = (function(superClass) {
    extend(UnknownUser, superClass);

    function UnknownUser(message) {
      this.message = message != null ? message : "Unknown user, please login first";
      this.name = 'UnknownUser';
      Error.captureStackTrace(this, UnknownUser);
    }

    return UnknownUser;

  })(Error);

  exports.Error = {
    UnknownUser: UnknownUser
  };

  exports.findGroups = function(req) {
    var Group, User;
    User = global.db.models.user;
    Group = global.db.models.group;
    if (!req.session.user) {
      return Group.findAll({
        where: {
          access_level: ['public', 'protect']
        },
        include: [
          {
            model: User,
            as: 'creator'
          }
        ]
      });
    }
    return User.find(req.session.user.id).then(function(user) {
      if (!user) {
        throw new UnknownUser();
      }
      return user.getGroups();
    }).then(function(groups) {
      var group, normalGroups;
      normalGroups = (function() {
        var i, len, results;
        results = [];
        for (i = 0, len = groups.length; i < len; i++) {
          group = groups[i];
          if (group.membership.access_level !== 'verifying') {
            results.push(group.id);
          }
        }
        return results;
      })();
      return Group.findAll({
        where: {
          $or: [
            {
              access_level: ['public', 'protect']
            }, {
              id: normalGroups
            }
          ]
        },
        include: [
          {
            model: User,
            as: 'creator'
          }
        ]
      });
    });
  };

}).call(this);

//# sourceMappingURL=utils.js.map
