// Generated by CoffeeScript 1.9.3
(function() {
  var express, modules, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  modules = require('./modules');

  router.use('/contest', modules.contest.router);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
