// Generated by CoffeeScript 1.9.3
(function() {
  var express, modules, router;

  express = require('express');

  router = express.Router({
    mergeParams: true
  });

  modules = require('./modules');

  router.use('/contests', modules.contest.router).use('/users', modules.user.router).use('/bcpc', modules.bcpc.router);

  module.exports = router;

}).call(this);

//# sourceMappingURL=router.js.map
