// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('message', {
      content: {
        type: DataTypes.STRING,
        allowNull: false
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=message.js.map
