// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('submission_code', {
      content: {
        type: DataTypes.TEXT
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=submission_code.js.map
