// Generated by CoffeeScript 1.9.2
(function() {
  module.exports = function(sequelize, DataTypes) {
    return sequelize.define('user', {
      username: {
        type: DataTypes.STRING,
        allowNull: false,
        validate: {
          isEmail: true,
          notEmpty: true
        }
      },
      password: {
        type: DataTypes.STRING,
        allowNull: false
      },
      description: {
        type: DataTypes.TEXT
      },
      school: {
        type: DataTypes.ENUM('北京航空航天大学', '北京邮电大学', '-----'),
        defaultValue: '-----'
      },
      college: {
        type: DataTypes.ENUM('软件工程', '计算机科学', '-----'),
        defaultValue: '-----'
      },
      student_id: {
        type: DataTypes.STRING
      },
      nickname: {
        type: DataTypes.STRING
      },
      is_super_admin: {
        type: DataTypes.BOOLEAN,
        defaultValue: false
      },
      last_login: {
        type: DataTypes.DATE
      }
    }, {
      underscored: true
    });
  };

}).call(this);

//# sourceMappingURL=user.js.map
